[package]
name = "try_from_expr"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
try_from_expr_derive = { path = "../try_from_expr_derive" }
ordered-float = { version = "5.0.0", features = ["serde"] }
syn = { workspace = true }
